version: '3.8'

services:
    postgres:
        container_name: postgres_db
        image: postgres:alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=socialMedia
            - POSTGRES_PASSWORD=socialMediaPassword
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
